version: "3.8"
services:
  db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${DB_USER:-odoo}
      POSTGRES_PASSWORD: ${DB_PASSWD:-secret}
  web:
    image: odoo:latest
    platform: "linux/amd64"
    depends_on:
      - db
    volumes:
      - ./etc:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      HOST: db
      USER: ${DB_USER:-odoo}
      PASSWORD: ${DB_PASSWD:-secret}
    ports:
      - 127.0.0.1:${WEB_PORT:-8069}:8069
      - 127.0.0.1:${CHAT_PORT:-8072}:8072
volumes:
  db_data:
